docker-compose-yaml: docker-compose.yml

project: kubernetes101

tasks:
  # pre-rollout:
  #   - run:
  #       name: drush sql-dump
  #       command: mkdir -p /app/web/sites/default/files/private/ && drush sql-dump --ordered-dump --gzip --result-file=/app/web/sites/default/files/private/pre-deploy-dump.sql.gz || true
  #       service: cli

  post-rollout:
    - run:
        name: IF no Drupal installed and we are not main branch, sync from main branch
        command: |
          if tables=$(drush sqlq "show tables like 'node';") && [ -z "$tables" ] && [[ "$LAGOON_ENVIRONMENT" != "main" ]]; then
              # no drupal installed, sync DB from main branch
              drush -y sql-sync @lagoon.kubernetes101-main @self
          fi
        service: cli
    - run:
        name: drush cim
        command: drush -y cim
        service: cli
    - run:
        name: drush updb
        command: drush -y updb
        service: cli
    - run:
        name: drush cr
        command: drush -y cr
        service: cli



environments:
  main:
    cronjobs:
      - name: drush cron
        schedule: "*/15 * * * *"
        command: drush cron
        service: cli
